"""Write hooks/sprites.generated.ts from the HD expression overlays and the pose frames."""
import json
import sys

from hd_variants import EXPRESSION_COLORS
from poses import POSE_COLORS

HEADER = """// GENERATED by tools/emit_hd.py from art/gen/*.png (Codex image generation). Do not edit.
import type { Palette } from './sprites'

/** Colours only the generated expressions use: sweat drop and blush. */
export const HD_EXPRESSION_COLORS: Palette = {expression}

/** Colours the pose props use: pencil gold, magic violet, pillow white, screen cyan. */
export const HD_POSE_COLORS: Palette = {poses}
"""


def palette_literal(colors):
    return "{ " + ", ".join(f"{k}: 0x{v:06x}" for k, v in colors.items()) + " }"


def rows_literal(rows, indent):
    pad = " " * indent
    return "[\n" + "\n".join(f"{pad}  '{row}'," for row in rows) + f"\n{pad}]"


def main():
    overlays = json.load(open(sys.argv[1]))
    poses = json.load(open(sys.argv[2]))["poses"]
    out = HEADER.replace("{expression}", palette_literal(EXPRESSION_COLORS)).replace("{poses}", palette_literal(POSE_COLORS))
    expressions = ",\n".join(f"  {name}: {rows_literal(rows, 2)}" for name, rows in overlays.items())
    out += f"\n/** Face overlays on the HD base: '.' keeps the base pixel. */\nexport const SAKURA_HD_EXPRESSION_ROWS = {{\n{expressions},\n}} as const\n"
    out += "\nexport type HdExpression = keyof typeof SAKURA_HD_EXPRESSION_ROWS\n"
    frames = ",\n".join(
        f"  {name}: [\n" + ",\n".join(f"    {rows_literal(rows, 4)}" for rows in frame_list) + ",\n  ]"
        for name, frame_list in poses.items()
    )
    out += f"\n/** Whole-body pose frames, 48x64, looped in order while the mood lasts. */\nexport const SAKURA_HD_POSES = {{\n{frames},\n}} as const\n"
    out += "\nexport type HdPose = keyof typeof SAKURA_HD_POSES\n"
    open(sys.argv[3], "w").write(out)


if __name__ == "__main__":
    main()
